include: package:flutter_lints/flutter.yaml

analyzer:
  # Keep defaults from flutter_lints; enable stricter raw-type checking while
  # still allowing the default Flutter scaffold to analyze cleanly.
  language:
    strict-raw-types: true

linter:
  rules:
    # Code cleanliness
    unused_import: true
    unused_local_variable: true

    # Production-safety: avoid print in committed code
    avoid_print: true

    # Prefer immutability and const where reasonable
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Dynamic / loose typing
    avoid_dynamic_calls: true

    # Pragmatic clarity rules (do not force explicit types everywhere)
    always_declare_return_types: true
    omit_local_variable_types: true

    # Async correctness
    unawaited_futures: true

